#!/bin/bash

INBOX_DIR="/var/spool/fsmsg/";
CURRENT_USER_INBOX="${INBOX_DIR}${USER}.inbox";

check_user_exists() {
    user_id=$(id -u "$1" 2>/dev/null)
    if [[ -z "$user_id" ]]; then
        echo "User $1 does not exist."
        exit 1
    fi
}

show_help() {
    echo "Usage: fsmsg [command] [arguments]"
    echo "Commands:"
    echo "  send [recipient] [message]  - Send a message to the recipient's inbox."
    echo "  show                        - Show messages in your inbox."
    echo "  check                       - Check if you have any new messages (useful on login)."
    echo "  clear                       - Clear all messages in your inbox."
    echo "  help                        - Display this help message."
}

if [[ $1 == "help" ]]; then
    show_help;
elif [[ $1 == "send" ]]; then
    if [[ -z "$2" || -z "$3" ]]; then
        show_help;
        exit 1;
    fi
    check_user_exists "$2";

    INBOX="${INBOX_DIR}${2}.inbox"

    if [[ ! -f "$INBOX" ]]; then
        touch "$INBOX"
        chmod 666 "$INBOX"
    fi

    echo "[$(date)] From $USER: ${@:3}" >> $INBOX;
    echo "Message sent to $2.";
elif [[ $1 == "show" ]]; then
    if [[ -f "$CURRENT_USER_INBOX" ]]; then
        echo "Messages in your inbox:";
        cat "$CURRENT_USER_INBOX";
    else
        echo "Your inbox is empty.";
    fi
elif [[ $1 == "clear" ]]; then
    if [[ -f "$CURRENT_USER_INBOX" ]]; then
        rm -f "$CURRENT_USER_INBOX";
        echo "Your inbox has been cleared.";
    else
        echo "Your inbox is already empty.";
    fi
elif [[ $1 == "check" ]]; then
    if [[ -f "$CURRENT_USER_INBOX" ]]; then
        echo "You have new messages in your inbox. Use 'fsmsg show' to read them.";
    else
        echo "No new messages.";
    fi
else
    show_help;
    exit 1;
fi
